name: build and test

on: [push]

jobs:
  compliance:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Advance Security Policy as Code
        uses: advanced-security/policy-as-code@v2.0
        with:
          policy: GeekMasher/security-queries
          policy-path: policies/default.yml

          token: ${{ secrets.ACCESS_TOKEN }}
          
          argvs: '--disable-dependabot --disable-secret-scanning --disable-code-scanning'

  build-maven:
    needs: compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: "maven"
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build with Maven
        run: mvn -B verify "-Dspring-boot.run.jvmArguments=-Dfile.encoding=UTF-8"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: itatm/dave-frontend:${{ env.GITHUB_REF_NAME_SLUG }}
